# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mongo1
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    # volumes:
    #   - dbdata6:/data/db
    networks:
      - my_network
    restart: on-failure
    # env_file:
    #   - .env

networks:
  my_network: